name: production

on:
  push:
    branches:
      - master

jobs:
  docker_deploy:
    uses: spuxx1701/ci/.github/workflows/docker_deploy.yml@v1.1
    with:
      username: spuxx
      repository: leopold-hock-web
      environment: production
    secrets:
      token: ${{ secrets.DOCKERHUB_TOKEN }}
      ssh_host: ${{ secrets.SSH_HOST }}
      ssh_username: ${{ secrets.SSH_USERNAME }}
      ssh_password: ${{ secrets.SSH_PASSWORD }}
