name: production

on:
  push:
    branches:
      - master

jobs:
  docker_build_and_push:
    uses: spuxx1701/ci/.github/workflows/docker_build_and_push.yml@v1.0
    with:
      username: spuxx
      repository: leopold-hock-web
      environment: production
    secrets:
      token: ${{ secrets.DOCKERHUB_TOKEN }}

  finish:
    needs: docker_build_and_push
    runs-on: ubuntu-latest
    steps:
      - id: log
        run: echo ${{ needs.docker_push.outputs.tags }}
